### ISSUE TITLE
Running the docker compose file shows Traefik dashboard but not Odoo

### ISSUE THREAD

**Issue by axelpina** [paraita/docker-compose-traefik-odoo-postgres#3]
I've been trying to get odoo up with this script but the only part of it that seems to come up is the traefik dashboard. When I try to access the container of the Odoo I installed, nothing comes up or gives me a `MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT` alert when I try to access it by the domain. 

This is how my `.env` looks like:

```
ODOO_USER= user
ODOO_PASS= password
ODOO_TRAEFIK_URL= test1.mydomain.com
TRAEFIK_DEFAULT_DOMAIN= mydomain.com
ACME_EMAIL= email@gmail.com
```

Part of me feels like like I'm inputting the details here wrong, and would like some clarification as to how should I input it.

Things I've already checked/tried:

- Verified the ports were open in the server
- Have tried restarting the container

**Comment by paraita** [comment]
thanks @AxelPina for reporting the issue, I'll have a look.
Could you post the output of `docker-compose logs` once all containers have started ? It shall help me investigate :)

**Comment by paraita** [comment]
Found it ! I forgot to mention in the README file that you also need to set the DB credentials in the `odoo/config/odoo.conf` file, then you should be good to go.

**Comment by paraita** [comment]
For the certificate problem, can you try to replace any reference of `odootest` with `oodo` in the docker-compose yaml file ?

**Comment by axelpina** [comment]
Will be testing today and will update you on it!

**Comment by axelpina** [comment]
This is what I get when I replace the `odootest` reference with `odoo`:

```root@ip-myip:~/docker-compose-traefik-odoo-postgres# docker-compose up -d
Creating docker-compose-traefik-odoo-postgres_db_1      ... done
Creating docker-compose-traefik-odoo-postgres_traefik_1 ... 
Creating docker-compose-traefik-odoo-postgres_odoo_1    ... 
Creating docker-compose-traefik-odoo-postgres_odoo_1    ... error
Creating docker-compose-traefik-odoo-postgres_traefik_1 ... done
postgres_odoo_1 (c5223d6f0044956b8e0d2733224f3e0a36b43d888e190f79e4326c9d3d61439e): Bind for 0.0.0.0:8069 failed: port is already allocated
ERROR: for odoo  Cannot start service odoo: driver failed programming external connectivity on endpoint docker-compose-traefik-odoo-postgres_odoo_1 (c5223d6f0044956b8e0d2733224f3e0a36b43d888e190f79e4326c9d3d61439e): Bind for 0.0.0.0:8069 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.root@ip-myip:~/docker-compose-traefik-odoo-postgres# ```

**Comment by axelpina** [comment]
This is what the `docker-compose logs` shows:

```Attaching to docker-compose-traefik-odoo-postgres_odoo_1, docker-compose-traefik-odoo-postgres_traefik_1, docker-compose-traefik-odoo-postgres_db_1
db_1       | 
db_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1       |
db_1       | 2020-01-31 14:55:38.115 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2020-01-31 14:55:38.115 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2020-01-31 14:55:38.120 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2020-01-31 14:55:38.141 UTC [24] LOG:  database system was shut down at 2020-01-31 14:49:56 UTC
db_1       | 2020-01-31 14:55:38.148 UTC [1] LOG:  database system is ready to accept connections
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="Configuration loaded from flags."
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="Traefik version 2.0.7 built on 2019-12-09T17:51:21Z"
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ trimPrefix `/` .Name }}. ategixtest.com`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"odoo\":{\"acme\":{\"email\":\" apina@ategix.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"web\"}}}}}"
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="No default certificate, generating one"
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Start TCP Server" entryPointName=traefik
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Start TCP Server" entryPointName=web
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Start TCP Server" entryPointName=websecure
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ trimPrefix `/` .Name }}. ategixtest.com`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":15000000000}"
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="Starting provider *acme.Provider {\"email\":\" apina@ategix.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"web\"},\"ResolverName\":\"odoo\",\"store\":{},\"ChallengeStore\":{}}"
traefik_1  | time="2020-01-31T14:55:39Z" level=info msg="Testing certificate renew..." providerName=odoo.acme
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Configuration received from provider odoo.acme: {\"http\":{},\"tls\":{}}" providerName=odoo.acme
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="No default certificate, generating one"
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Provider connection established with docker 19.03.5 (API 1.40)" providerName=docker
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"db-docker-compose-traefik-odoo-postgres\":{\"service\":\"db-docker-compose-traefik-odoo-postgres\",\"rule\":\"Host(`db-docker-compose-traefik-odoo-postgres. ategixtest.com`)\"},\"portainer\":{\"service\":\"portainer\",\"rule\":\"Host(`portainer. ategixtest.com`)\"},\"traefik-docker-compose-traefik-odoo-postgres\":{\"service\":\"traefik-docker-compose-traefik-odoo-postgres\",\"rule\":\"Host(`traefik-docker-compose-traefik-odoo-postgres. ategixtest.com`)\"}},\"services\":{\"db-docker-compose-traefik-odoo-postgres\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.24.0.2:5432\"}],\"passHostHeader\":true}},\"portainer\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.17.0.2:8000\"}],\"passHostHeader\":true}},\"traefik-docker-compose-traefik-odoo-postgres\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.25.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [web websecure traefik]" routerName=traefik-docker-compose-traefik-odoo-postgres@docker
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [web websecure traefik]" routerName=db-docker-compose-traefik-odoo-postgres@docker
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [web websecure traefik]" routerName=portainer@docker
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining routerName=traefik-docker-compose-traefik-odoo-postgres@docker serviceName=traefik-docker-compose-traefik-odoo-postgres entryPointName=web
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating load-balancer" serviceName=traefik-docker-compose-traefik-odoo-postgres entryPointName=web routerName=traefik-docker-compose-traefik-odoo-postgres@docker
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating server 0 http://172.25.0.2:80" entryPointName=web routerName=traefik-docker-compose-traefik-odoo-postgres@docker serviceName=traefik-docker-compose-traefik-odoo-postgres serverName=0
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Added outgoing tracing middleware traefik-docker-compose-traefik-odoo-postgres" routerName=traefik-docker-compose-traefik-odoo-postgres@docker middlewareType=TracingForwarder middlewareName=tracing entryPointName=web
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating middleware" routerName=db-docker-compose-traefik-odoo-postgres@docker entryPointName=web serviceName=db-docker-compose-traefik-odoo-postgres middlewareName=pipelining middlewareType=Pipelining
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating load-balancer" routerName=db-docker-compose-traefik-odoo-postgres@docker entryPointName=web serviceName=db-docker-compose-traefik-odoo-postgres
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating server 0 http://172.24.0.2:5432" routerName=db-docker-compose-traefik-odoo-postgres@docker entryPointName=web serviceName=db-docker-compose-traefik-odoo-postgres serverName=0
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Added outgoing tracing middleware db-docker-compose-traefik-odoo-postgres" entryPointName=web routerName=db-docker-compose-traefik-odoo-postgres@docker middlewareName=tracing middlewareType=TracingForwarder
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating middleware" middlewareType=Pipelining entryPointName=web routerName=portainer@docker serviceName=portainer middlewareName=pipelining       
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=portainer@docker serviceName=portainer
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating server 0 http://172.17.0.2:8000" routerName=portainer@docker serviceName=portainer serverName=0 entryPointName=web
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Added outgoing tracing middleware portainer" routerName=portainer@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=web  
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik_1  | time="2020-01-31T14:55:39Z" level=debug msg="No default certificate, generating one"
traefik_1  | time="2020-01-31T14:57:20Z" level=error msg="Error while Peeking first byte: read tcp 172.24.0.3:80->185.153.199.246:16548: read: connection reset by peer"
traefik_1  | time="2020-01-31T15:05:39Z" level=warning msg="A new release has been found: 2.1.3. Please consider updating."```

**Comment by axelpina** [comment]
I ran a test removing the `ports` section from odoo's part in the .yml fine but it didn't work. Also tried adding port 8069 in the traefiko `port` section but nothing. Still confused as to what it could be.

**Comment by paraita** [comment]
From the logs, it look like something is already using the 8069 port, can you try to check if that's the case ? (do a `docker ps` and copy/paste the output here).
You can also try to use another port since 8069 looks taken, to do so modify this part in the docker-compose yaml file:

```
ports:
  - "9069:8069"
  - "9072:8072"
```

So you should be able to reach your Odoo server at http://localhost:9069 (if you run this docker-compose file locally).
For the SSL certificate Traefik relies on Let's Encrypt so the machine you are using with the docker-compose file needs to be reachable from a domain with a real domain.

I don't think Traefik is going to mess up with the Odoo container since it's only providing another way to reach your Odoo server (ports 80/443).

**Comment by axelpina** [comment]
> 
> 
> From the logs, it look like something is already using the 8069 port, can you try to check if that's the case ? (do a `docker ps` and copy/paste the output here).

This was because I was testing and added the ports themselves to the traefik `ports` section.

> You can also try to use another port since 8069 looks taken, to do so modify this part in the docker-compose yaml file:
> 
> ```
> ports:
>   - "9069:8069"
>   - "9072:8072"
> ```
> 
> So you should be able to reach your Odoo server at http://localhost:9069 (if you run this docker-compose file locally).

Tried this and it didn't work :/

> For the SSL certificate Traefik relies on Let's Encrypt so the machine you are using with the docker-compose file needs to be reachable from a domain with a real domain.
> 

I am using AWS LightSail and I've created a DNS zone and proceeded to attach the domain to the instance as well created the records.

> I don't think Traefik is going to mess up with the Odoo container since it's only providing another way to reach your Odoo server (ports 80/443).

When I run the yml, traefik runs perfectly fine but odoo wont work. When I try reaching the test1.mycompany.com domain it shows a warning then a 404 page not found error.

I'm really not sure what it could be still. Is it possible that you could run a test?

**Comment by axelpina** [comment]
> Found it ! I forgot to mention in the README file that you also need to set the DB credentials in the odoo/config/odoo.conf file, then you should be good to go.

I am filling the ones that were mentioned in the README which are `db_user` & `db_password`. Which ones do I need to fill?

**Comment by paraita** [comment]
> I am using AWS LightSail and I've created a DNS zone and proceeded to attach the domain to the instance as well created the records.

Have you managed to access Traefik's dashboard ? Just to make sure the machine is accessible through its domain.

> I am filling the ones that were mentioned in the README which are db_user & db_password. Which ones do I need to fill?

You'll need to fill the following fields inside the `odoo/config/odoo.conf` file. You gotta reuse the same user/password that you've used in the `.env` file:

* db_user
* db_password

**Comment by paraita** [comment]
I've run some tests using Digital Ocean but I'll have a look at AWS Lightsail too :)

**Comment by axelpina** [comment]
> Have you managed to access Traefik's dashboard ? Just to make sure the machine is accessible through its domain.

Yes. I can access the Traefik Dashboard & see the containers and services.

> You'll need to fill the following fields inside the odoo/config/odoo.conf file. You gotta reuse the same user/password that you've used in the .env file:

    db_user
    db_password

Yup. I've been doing this but still nothing.

**Comment by axelpina** [comment]
Another finding. After clearing the browser cache now a message appears saying `Bad Gateway` when I input `test1.mycompany.com` domain.

If I am correct bad gateway means the web front end can't reach its back end / origin server, so I have a connection problem between them.

I have the 3 containers up right now. Odoo, postres and traefik. When I `docker logs --details` both posgres containers it gives me the following errors:

**Odoo container:**

> Database connection failure: FATAL:  password authentication failed for user "myuser"
> Database connection failure: FATAL:  password authentication failed for user "myuser"

**Postgres container:**

`2020-02-03 16:53:25.592 UTC [1257] FATAL:  password authentication failed for user "myuser"
 2020-02-03 16:53:25.592 UTC [1257] DETAIL:  Role "myuser" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
 2020-02-03 16:53:26.596 UTC [1258] FATAL:  password authentication failed for user "myuser"
 2020-02-03 16:53:26.596 UTC [1258] DETAIL:  Role "myuser" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
 2020-02-03 16:53:27.599 UTC [1259] FATAL:  password authentication failed for user "myuser"
 2020-02-03 16:53:27.599 UTC [1259] DETAIL:  Role "myuser" does not exist.`

**Comment by paraita** [comment]
Hi @AxelPina I've tried running the master a few minutes ago with the following files without any problems:

`.env`:

```
ODOO_USER=paraita
ODOO_PASS=paraita
ODOO_TRAEFIK_URL=testdocker.hipopochat.com
TRAEFIK_DEFAULT_DOMAIN=hipopochat.com
ACME_EMAIL=<my email address>
```

`docker-compose.yml`:

```
version: "3"
services:
  odoo:
    image: odoo:12.0
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=db
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASS}
    volumes:
      - ./odoo/odoo-web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/logs:/var/log/odoo
    labels:
      - 'traefik.http.routers.odoo.rule=Host(`${ODOO_TRAEFIK_URL}`)'
      - 'traefik.http.routers.odoo.entrypoints=websecure'
      - 'traefik.http.routers.odoo.tls.certresolver=odoo'
      - 'traefik.port=8069'
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  db:
    image: postgres:10
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${ODOO_USER}
      - POSTGRES_PASSWORD=${ODOO_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  traefik:
    image: traefik:v2.0
    networks:
      - internal
      - web
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/etc/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
     - "--log.level=DEBUG"
     - "--api.insecure=true"
     - "--providers.docker"
     - "--providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.${TRAEFIK_DEFAULT_DOMAIN}`)"
     - "--entryPoints.web.address=:80"
     - "--entryPoints.websecure.address=:443"
     - "--certificatesResolvers.odootest.acme.httpchallenge=true"
     - "--certificatesresolvers.odootest.acme.httpchallenge.entrypoint=web"
     - "--certificatesresolvers.odootest.acme.email=${ACME_EMAIL}"
     - "--certificatesresolvers.odootest.acme.storage=/letsencrypt/acme.json"

networks:
  internal:
  web:
      external: true
```

`odoo/config/odoo.conf`:

```
[options]
addons_path = /mnt/extra-addons
csv_internal_sep = ,
data_dir = /var/lib/odoo
db_host = db
db_maxconn = 64
db_name = False
db_password = paraita
db_port = 5432
db_sslmode = prefer
db_template = template0
db_user = paraita
dbfilter =
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 3600
limit_time_real = 3600
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = debug
logfile = /var/log/odoo/odoo.log
logrotate = True
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = 1
reportgz = False
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file = False
test_tags = None
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 2
```

These are the steps I've followed to try to reproduce your problem:

0) I've provisioned a fresh VM from Digital Ocean
1) followed [this](https://docs.docker.com/install/linux/docker-ce/ubuntu/) and [that](https://docs.docker.com/compose/install/) to install docker and docker-compose
2) Pointed my `testdocker.hipopochat.com` domain to that VM
3) `git clone https://github.com/paraita/docker-compose-traefik-odoo-postgres.git testdocker`
4) chmod -R 0777 testdocker (for the sake of it)
5) cd testdocker
6) applied the given settings to the configuration files
7) `docker-compose up -d`

Based on the logs you've provided, the postgresql container config didn't go well, can you make sure you are starting from a clean state ? (shutting down the containers using `docker-compose down` and pruning all existing cache/containers/images)
