### ISSUE TITLE
Trying to get Odoo working behind Traefik and your example looks reasonable except for a few details.

### ISSUE THREAD

**Issue by Leopere** [paraita/docker-compose-traefik-odoo-postgres#9]
I'm wondering about a couple of decisions you've made.
https://github.com/paraita/docker-compose-traefik-odoo-postgres/blob/master/docker-compose.yml#L51-L54
```yaml
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/etc/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
Why have you given Traefik the ability to write to `docker.sock` instead of `- "/var/run/docker.sock:/var/run/docker.sock:ro" for read-only?  Do you really need Traefik to have root system access on the host OS?

How come you have two uncommitted mounts?  I'd love to see even an example of your `traefik.yml` and potentially even just why you couldn't establish all of the settings from the yaml in docker labels or the Traefik invocation `CMD`

I'd really like to completely do away with Traefik configs if I migrate to Traefik 2.0 from 1.7 if possible.

**Comment by paraita** [comment]
Hi @Leopere thanks for reaching out ! 


> Why have you given Traefik the ability to write to docker.sock instead of `- "/var/run/docker.sock:/var/run/docker.sock:ro" for read-only? Do you really need Traefik to have root system access on the host OS?

Traefik doesn't need write permission to the socket, I was just being lazy, you can specify the `ro` flag. Actually you can set it on all mounted items, Traefik never writes to those.
 
> How come you have two uncommitted mounts? I'd love to see even an example of your traefik.yml and potentially even just why you couldn't establish all of the settings from the yaml in docker labels or the Traefik invocation CMD

I believe it is possible to have all of the settings in either the CMD invocation or the docker labels. At the time of writing this repository, I was also migrating from Traefik 1.x to Trafik 2.x
Thinking about it, I am not sure if the dynamic config would work if you pass those as labels. I'll try finishing migrating the configuration to docker-labels only, but if you feel like opening a PR you're welcome :)

Here's an example setup I have in a dev environment:

my docker-compose.yml:
```docker-compose.yml
version: "3"

services:
  traefik:
    networks:
      - traefiknet
    ports:
      - "443:443"
      - "80:80"
      - "8081:8080"
    volumes:
      - "./certs:/etc/certs:ro"
      - "./dyn_conf.yml:/etc/traefik/dyn_conf.yml:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    image: traefik:latest
    restart: unless-stopped

networks:
  traefiknet:
    external:
      name: traefik_default
```

Traefik.yml:
```traefik.yml
# Docker configuration backend
providers:
  file:
    filename: /etc/traefik/dyn_conf.yml
    watch: true
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.redacted.domain`)"

# API and dashboard configuration
api:
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
```
dyn_conf.yml:
```dyn_conf.yml
# Security
serversTransport:
  insecureSkipVerify: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/poudlard-cert.pem
        keyFile: /etc/certs/poudlard-key.pem
  certificates:
    - certFile: /etc/certs/poudlard-cert.pem
      keyFile: /etc/certs/poudlard-key.pem
```

The structure of the files is the following:
![image](https://user-images.githubusercontent.com/1413759/98040566-8c535880-1dc4-11eb-885a-2500af3bca37.png)

**Comment by Leopere** [comment]
Thank you so much for your response!  This is very helpful thank you yes!  :) I would almost suggest even putting this into the repo under the README.md

**Comment by Leopere** [comment]
I'm getting a bit closer with this now that you've shown these features however now I'm stuck with the fact that the `odoo/odoo.conf` didn't really pull variables correctly so I'm going to avoid using the `.env` eventually however if you could have a look http://odoo.nixc.us:8080/dashboard/#/http/routers it seems that the db container is getting routed to for some reason?

```
root@odoo:~/odoo# docker-compose stop odoo && docker-compose rm -f odoo && docker-compose up -d odoo && docker-compose logs -f odoo
Stopping odoo_odoo_1 ... done
Going to remove odoo_odoo_1
Removing odoo_odoo_1 ... done
odoo_db_1 is up-to-date
Creating odoo_odoo_1 ... done
Attaching to odoo_odoo_1
odoo_1     | WARNING: built-in log rotation is not reliable in multi-worker scenarios and may incur significant data loss. It is strongly recommended to use an external log rotation utility or use system loggers (--syslog) instead.
odoo_1     | ERROR: couldn't create the logfile directory. Logging to the standard output.
odoo_1     | 2020-11-16 21:05:27,028 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
odoo_1     | 2020-11-16 21:05:27,029 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
odoo_1     | 2020-11-16 21:05:27,031 1 DEBUG ? odoo.netsvc: logger level set: ":INFO"
odoo_1     | 2020-11-16 21:05:27,032 1 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
odoo_1     | 2020-11-16 21:05:27,032 1 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
odoo_1     | 2020-11-16 21:05:27,033 1 DEBUG ? odoo.netsvc: logger level set: ":INFO"
odoo_1     | 2020-11-16 21:05:27,033 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,033 1 INFO ? odoo: Odoo version 12.0-20201112
odoo_1     | 2020-11-16 21:05:27,033 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
odoo_1     | 2020-11-16 21:05:27,033 1 INFO ? odoo: addons paths: ['/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
odoo_1     | 2020-11-16 21:05:27,034 1 INFO ? odoo: database: odoo@db:5432
odoo_1     | 2020-11-16 21:05:27,034 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,052 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,054 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,056 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,290 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
odoo_1     | 2020-11-16 21:05:27,323 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,325 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,419 1 DEBUG ? odoo.tools.translate: translation went wrong for "'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.'", skipped
odoo_1     | 2020-11-16 21:05:27,526 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,529 1 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:27,532 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
odoo_1     | 2020-11-16 21:05:27,534 1 DEBUG ? odoo.service.server: Multiprocess starting
odoo_1     | 2020-11-16 21:05:27,545 30 INFO ? odoo.service.server: Worker WorkerHTTP (30) alive
odoo_1     | 2020-11-16 21:05:27,550 31 INFO ? odoo.service.server: Worker WorkerHTTP (31) alive
odoo_1     | 2020-11-16 21:05:27,572 33 INFO ? odoo.service.server: Worker WorkerCron (33) alive
odoo_1     | 2020-11-16 21:05:27,598 36 INFO ? odoo.service.server: Worker WorkerCron (36) alive
odoo_1     | WARNING: built-in log rotation is not reliable in multi-worker scenarios and may incur significant data loss. It is strongly recommended to use an external log rotation utility or use system loggers (--syslog) instead.
odoo_1     | ERROR: couldn't create the logfile directory. Logging to the standard output.
odoo_1     | 2020-11-16 21:05:30,374 32 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
odoo_1     | 2020-11-16 21:05:30,375 32 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
odoo_1     | 2020-11-16 21:05:30,377 32 DEBUG ? odoo.netsvc: logger level set: ":INFO"
odoo_1     | 2020-11-16 21:05:30,377 32 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
odoo_1     | 2020-11-16 21:05:30,378 32 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
odoo_1     | 2020-11-16 21:05:30,379 32 DEBUG ? odoo.netsvc: logger level set: ":INFO"
odoo_1     | 2020-11-16 21:05:30,379 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:30,379 32 INFO ? odoo: Odoo version 12.0-20201112
odoo_1     | 2020-11-16 21:05:30,379 32 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
odoo_1     | 2020-11-16 21:05:30,379 32 INFO ? odoo: addons paths: ['/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
odoo_1     | 2020-11-16 21:05:30,382 32 INFO ? odoo: database: odoo@db:5432
odoo_1     | 2020-11-16 21:05:30,382 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,330 32 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
odoo_1     | 2020-11-16 21:05:31,350 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,352 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,432 32 DEBUG ? odoo.tools.translate: translation went wrong for "'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.'", skipped
odoo_1     | 2020-11-16 21:05:31,509 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,510 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,513 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,527 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:31,528 32 DEBUG ? odoo.tools.config: Failed to create addons data dir /var/lib/odoo/addons/12.0
odoo_1     | 2020-11-16 21:05:32,332 32 INFO ? odoo.service.server: Evented Service (longpolling) running on 0.0.0.0:8072

```
```yaml
version: "3"
services:
  odoo:
    image: odoo:12.0
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo/odoo-web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/logs:/var/log/odoo
    labels:
      - 'traefik.http.routers.odoo.rule=Host(`odoo.example.com`)'
      - 'traefik.http.routers.odoo.entrypoints=websecure'
      - 'traefik.http.routers.odoo.tls.certresolver=odoo'
      - "traefik.http.services.odoo.loadbalancer.server.port=8069"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  db:
    image: postgres:10
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  traefik:
    image: traefik:v2.0
    networks:
      - internal
      - web
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/etc/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
     - "--log.level=DEBUG"
     - "--api.insecure=true"
     - "--providers.docker"
     - "--providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.${TRAEFIK_DEFAULT_DOMAIN}`)"
     - "--entryPoints.web.address=:80"
     - "--entryPoints.websecure.address=:443"
     - "--certificatesResolvers.odoo.acme.httpchallenge=true"
     - "--certificatesresolvers.odoo.acme.httpchallenge.entrypoint=web"
     - "--certificatesresolvers.odoo.acme.email=${ACME_EMAIL}"
     - "--certificatesresolvers.odoo.acme.storage=/letsencrypt/acme.json"

networks:
  internal:
  web:
      external: false
```
